version: '2'
services:
    msgatewayapplication-app:
        image: msgatewayapplication
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://msgatewayapplication-mysql:3306/msgatewayapplication?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    msgatewayapplication-mysql:
        extends:
            file: mysql.yml
            service: msgatewayapplication-mysql
